# Generated by Django 4.0.2 on 2022-02-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choises_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='chise_text',
            new_name='choice_text',
        ),
    ]
